export const LOGINDATA = {
  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_STOP: 'LOGIN_STOP',
};

export const SIGNIN_DATA = {
  SIGNIN_START: 'SIGNIN_START',
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_STOP: 'SIGNIN_STOP',
};
